name: "\U0001F41E Bug report"
description: Report a bug with Sessionic
labels: ['triage: bug']
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide th steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: In which version of Sessionic does this bug occur?
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: In which browser does this bug occur?
      placeholder: e.g. Firefox 115, Chrome 105, etc..
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Browser
      description: In which operating system does this bug occur?
      placeholder: e.g. Windows 10, Windows 11, Ubuntu, Arch Linux, macOS 13 etc..
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of this bug
      options:
        - annoyance
        - severe
        - blocking all usage of Sessionic
